# Generated by Django 2.1.3 on 2018-11-14 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=100)),
                ('email_address', models.EmailField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.PositiveIntegerField(max_length=100)),
                ('age', models.PositiveIntegerField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('cell', models.CharField(max_length=100)),
            ],
        ),
    ]
